# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a686d62c73e70189cde075302269a01c9e0c15569976e4ceeb5c15456e35bb3f1bd0267ba00fe98f78ec32744a160f32c2a03296594e5f3a06209df65d99458

test:
  secret_key_base: 32aaf94bee735ba16554208eaf5f909061769bed5a819a4b6668a0d5c857f1355c5bd4a9d994a2396e9169a6be125ab0c562b4ff0ad569ddea3e954be4d1a80e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
